spring.application.name=ifood.merchant.api

# Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ifood_merchant?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Credenciais do iFood
ifood.client.id=${IFOOD_CLIENT_ID}
ifood.client.secret=${IFOOD_CLIENT_SECRET}
ifood.merchant.id=d102dcc7-4c89-48c1-8013-6edc36af90bb